language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
script:
  - "npm run table:create"
  - "npm run seed:admin"
  - "npm run test"
after_success:
  - "npm run coverage"

services:
  - postgresql

before_script:
- psql -c 'create database travis_ci_test;' -U postgres

env:
  global:
  - DATABASE_URL=postgres://postgres:@localhost:5432/travis_ci_test
