language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
script:
  - "npm run table:create"
  - "npm run coverage"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

services:
  - postgresql

before_script:
- psql -c 'create database travis_ci_test;' -U postgres

env:
  global:
  - DATABASE_URL=postgres://postgres:@localhost:5432/travis_ci_test
